# Mendefinisikan versi Api yang digunakan v1
apiVersion: v1

# Mendefinisikan resource sebagai Service
kind: Service

# Mendefinisikan nama Service 'karsajobs' dan label 'backend'
metadata:
  labels:
    app: backend
  name: karsajobs

# Menentukan Spesifikasi
spec:

  # Mengekspos port 8080
  ports:
  - port: 8080

  # Menargetkan Pod yang memiliki Label type backend
  selector:
    type: backend

  # Memakai tipe NodePort.
  type: NodePort
