# Mendefinisikan versi Api yang digunakan v1
apiVersion: v1

# Mendefinisikan resource sebagai Secret
kind: Secret

# Mendefinisikan nama sebagai mongodb-secret
metadata:
  name: mongodb-secret

# Mendefinisikan nilai MONGO_ROOT_USERNAME untuk login
stringData:
  MONGO_ROOT_USERNAME: admin

# Mendefinisikan nilai MONGO_ROOT_PASSWORD untuk login, nilai string 'supersecretpassword' sudah diubah menjadi format base64
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
